### ISSUE TITLE
What type of tests should we provide ? 

### ISSUE THREAD

**Issue by lesommer** [lesommer/oocgcm#17]
random list of question / ideas
- provide nc data
- a test forlder
- use pytest / travis.

**Comment by lesommer** [comment]
see [this list of examples](http://pytest.org/latest/example/index.html#examples)

**Comment by rabernat** [comment]
I would definitely do [unit tests](https://en.wikipedia.org/wiki/Unit_testing) in addition to integration tests.

**Comment by lesommer** [comment]
I agree. I have started to include some simple tests for grid objects build from lat/lon arrays : see this
[commit](https://github.com/lesommer/oocgcm/commit/e8bda9ee5714e4ea6ad0468e017b86e052141df5). I guess I should also provide a light netcdf file to test grid objects build from files.

**Comment by rabernat** [comment]
The [coverage report](https://codecov.io/github/lesommer/oocgcm?branch=master) tells you how complete your test battery is.

**Comment by lesommer** [comment]
very limited coverage so far indeed. ;-) 

I am slowly switching to a more test-driven approach to coding. I am not a good software carpenter yet !

**Comment by lesommer** [comment]
Here is a simple [notebook](https://github.com/lesommer/notebooks/blob/master/Build_TestData_oocgcm.ipynb) that creates files for testing the creation of generic grid from nemo files.:

**Comment by lesommer** [comment]
@serazing suggests that we also use [doctest](https://pymotw.com/2/doctest/) for testing functions.

**Comment by lesommer** [comment]
basic unit test using netCDF files have been included to the test suite.
we should keep in mind to provide only NETCDF3 files in order to pass the ci build with scipy.

**Comment by lesommer** [comment]
I have added a test of the computation of horizontal gradients in oocgcm/test/.

**Comment by lesommer** [comment]
a priori, all the new methods should come with a unit test. some function could be tested with doctest. issue closed.
